version: '3'
services:
  todo-app:
    build: ./ToDo-App
    ports:
      - 8080:8080
#    environment:
#      - MONGO_URI=${MONGO_URI}
#      - MONGO_DB=${MONGO_DB}
  todo-front:
    build: ./ToDo-Front/todo-application-client
    ports:
      - 3000:80
